# -*- coding: utf-8 -*-
"""kadai_007.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rnEDB7MT5ljxQ2nP5DsI7onOBZwOPk7u
"""

array = ["月曜日は晴れです","火曜日は雨です", "水曜日は晴れです","木曜日は晴れです","金曜日は曇りです", "土曜日は曇りのち雨です", "日曜日は雷雨です"]

dictionary ={"mon": "晴れ", "tue":"雨", "wed":"晴れ", "thu":"晴れ", "fri":"曇り", "sat":"曇のち雨", "sun":"雷雨"}

print(array[2])
print(dictionary["wed"])