# -*- coding: utf-8 -*-
"""kadai_008

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1na__xHKzsFFDsKBx4u6ksolWHnwhuzrS
"""

var = 22

if var%3 == 0:
  print("FIZZ")

elif var%5 == 0:
  print("BUZZ")

else:
  print("FIZZBUZZ")